from __future__ import annotations

import json
import os
import subprocess
import tempfile
import uuid

from flask import Flask, flash, jsonify, redirect, render_template, request, send_file, url_for

from github_agent.agent import Agent
from github_agent.github_api import GitHubAPI, GitHubAPIError
from github_agent.llm import OllamaLLM
from github_agent.multi_agent import MultiAgentOrchestrator
from github_agent.tools import Tools
from github_agent.types import AgentConfig

APP = Flask(__name__)
APP.secret_key = os.environ.get("REVIEW_AGENT_SECRET", str(uuid.uuid4()))

OLLAMA_MODEL = "llama3:8b"
OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")

REPORTS: dict[str, dict] = {}
PENDING_DRAFTS: dict[str, dict] = {}
IMPROVE_RESULTS: dict[str, dict] = {}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _create_llm() -> OllamaLLM:
    return OllamaLLM(model=OLLAMA_MODEL, host=OLLAMA_HOST)


def _parse_github_repo(repo_input: str) -> tuple[str, str]:
    """Return (owner, repo_name) from a GitHub URL, owner/repo string, or local path."""
    s = (repo_input or "").strip().rstrip("/")
    if s.endswith(".git"):
        s = s[:-4]

    if "github.com" in s:
        after = s.split("github.com/")[-1]
        parts = [p for p in after.split("/") if p]
        if len(parts) >= 2:
            return parts[0], parts[1]
        return "", ""

    # owner/repo shorthand (not a file path)
    if "/" in s and not s.startswith("/") and not s.startswith(".") and s.count("/") == 1:
        parts = s.split("/")
        return parts[0], parts[1]

    # local path — try git remote
    local = s or "."
    try:
        r = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=local, capture_output=True, text=True, timeout=5,
        )
        if r.returncode == 0 and r.stdout.strip():
            return _parse_github_repo(r.stdout.strip())
    except Exception:
        pass
    return "", ""


def _local_path(repo_input: str) -> str:
    """Return the local filesystem path for git operations."""
    s = (repo_input or "").strip()
    if (
        "github.com" in s
        or (s and "/" in s and not s.startswith("/") and not s.startswith(".") and s.count("/") == 1)
    ):
        return "."
    return s or "."


def _package_to_dict(package) -> dict:
    draft = package.draft
    reflection = package.reflection

    if package.draft_type == "issue":
        draft_dict = {
            "title": draft.title,
            "problem_description": draft.problem_description,
            "evidence": draft.evidence,
            "acceptance_criteria": draft.acceptance_criteria,
            "risk_level": draft.risk_level,
            "labels": draft.labels,
        }
    else:
        draft_dict = {
            "title": draft.title,
            "summary": draft.summary,
            "files_affected": draft.files_affected,
            "behavior_change": draft.behavior_change,
            "test_plan": draft.test_plan,
            "risk_level": draft.risk_level,
            "base_branch": draft.base_branch,
        }

    return {
        "draft_type": package.draft_type,
        "draft": draft_dict,
        "reflection": {
            "passed": reflection.passed,
            "unsupported_claims": reflection.unsupported_claims,
            "missing_evidence": reflection.missing_evidence,
            "missing_tests": reflection.missing_tests,
            "policy_violations": reflection.policy_violations,
            "suggestions": reflection.suggestions,
            "overall_quality": reflection.overall_quality,
        },
        "reviewer_summary": package.reviewer_summary,
    }


def _format_issue_body(draft: dict) -> str:
    criteria = "\n".join(f"- [ ] {c}" for c in draft.get("acceptance_criteria", []))
    return (
        f"## Problem Description\n\n{draft.get('problem_description', '')}\n\n"
        f"## Evidence\n\n{draft.get('evidence', '')}\n\n"
        f"## Acceptance Criteria\n\n{criteria or '- [ ] TBD'}\n\n"
        f"**Risk Level:** {draft.get('risk_level', 'medium').upper()}\n\n"
        "_Generated by GitHub Review Agent_"
    )


def _format_pr_body(draft: dict) -> str:
    files = "\n".join(f"- `{f}`" for f in draft.get("files_affected", []))
    return (
        f"## Summary\n\n{draft.get('summary', '')}\n\n"
        f"## Files Affected\n\n{files or '_See diff_'}\n\n"
        f"## Behavior Change\n\n{draft.get('behavior_change', '')}\n\n"
        f"## Test Plan\n\n{draft.get('test_plan', '')}\n\n"
        f"**Risk Level:** {draft.get('risk_level', 'medium').upper()}\n\n"
        "_Generated by GitHub Review Agent_"
    )


def _format_improvement_comment(improved: dict, content_type: str, critique: dict) -> str:
    issues_found = []
    for key in ("vague_language", "missing_information", "unclear_criteria", "structural_problems"):
        items = critique.get(key, [])
        if items:
            issues_found.append(f"**{key.replace('_', ' ').title()}:** " + "; ".join(str(x) for x in items))
    critique_summary = "\n".join(f"- {line}" for line in issues_found) or "- No major issues found."

    if content_type == "issue":
        criteria = "\n".join(f"- [ ] {c}" for c in improved.get("acceptance_criteria", []))
        body = (
            f"**Suggested Title:** {improved.get('title', '')}\n\n"
            f"**Improved Description:**\n{improved.get('problem_description', '')}\n\n"
            f"**Evidence:**\n{improved.get('evidence', '')}\n\n"
            f"**Acceptance Criteria:**\n{criteria or '- [ ] TBD'}\n\n"
            f"**Risk Level:** {improved.get('risk_level', 'medium').upper()}"
        )
    else:
        files = "\n".join(f"- `{f}`" for f in improved.get("files_affected", []))
        body = (
            f"**Suggested Title:** {improved.get('title', '')}\n\n"
            f"**Improved Summary:**\n{improved.get('summary', '')}\n\n"
            f"**Files Affected:**\n{files or '_Not specified_'}\n\n"
            f"**Behavior Change:**\n{improved.get('behavior_change', '')}\n\n"
            f"**Test Plan:**\n{improved.get('test_plan', '')}\n\n"
            f"**Risk Level:** {improved.get('risk_level', 'medium').upper()}"
        )

    return (
        "## Improvement Suggestion\n\n"
        "_Generated by GitHub Review Agent._\n\n"
        "### Issues in Current Version\n\n"
        f"{critique_summary}\n\n"
        "---\n\n"
        "### Proposed Improved Version\n\n"
        f"{body}\n"
    )


# ---------------------------------------------------------------------------
# Task 1 — Review
# ---------------------------------------------------------------------------


@APP.route("/")
def index():
    return render_template("index.html")


@APP.route("/review", methods=["POST"])

def review():
    repo_input = request.form.get("repo", ".").strip()
    compare_mode = request.form.get("compare_mode", "branch")
    from_commit = request.form.get("from_commit", "").strip()
    to_commit = request.form.get("to_commit", "").strip()
    base_branch = request.form.get("base_branch", "").strip() or None
    token = request.form.get("token", "").strip()

    local_path = _local_path(repo_input)
    github_owner, github_repo_name = _parse_github_repo(repo_input)

    cfg = AgentConfig(repo=local_path, model=OLLAMA_MODEL, host=OLLAMA_HOST, temperature=0.0, verbose=False)
    agent = Agent(cfg)

    # Always use the LLM for model override (no skipping)

    try:
        if compare_mode == "commits":
            if from_commit and to_commit:
                result = agent.review_commits(f"{from_commit}..{to_commit}", use_colors=False, render_report=False)
            elif from_commit:
                result = agent.review_commits(f"{from_commit}~1..{from_commit}", use_colors=False, render_report=False)
            else:
                flash("Enter at least one commit hash when using Commits mode.", "warning")
                return redirect(url_for("index"))
        else:
            result = agent.review_branch(base_branch, use_colors=False, render_report=False)
    except Exception as exc:
        flash(f"Review failed: {exc}", "danger")
        return redirect(url_for("index"))

    if not result.ok:
        flash(result.details, "danger")
        return redirect(url_for("index"))

    summary = result.summary or {}
    report_id = str(uuid.uuid4())
    REPORTS[report_id] = {
        "summary": summary,
        "repo_input": repo_input,
        "local_path": local_path,
        "github_owner": github_owner,
        "github_repo": github_repo_name,
        "compare_mode": compare_mode,
        "from_commit": from_commit,
        "to_commit": to_commit,
        "base_branch": base_branch,
        "token": token,
    }

    return render_template("review.html", summary=summary, report_id=report_id, report=REPORTS[report_id])


@APP.route("/download_report")
def download_report():
    report_id = request.args.get("id")
    if not report_id or report_id not in REPORTS:
        return "Report not found", 404
    with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as tmp:
        tmp.write(json.dumps(REPORTS[report_id], indent=2).encode())
        tmp_path = tmp.name
    return send_file(tmp_path, as_attachment=True, download_name="review_report.json", mimetype="application/json")


# ---------------------------------------------------------------------------
# Task 2 — Draft & Create Issue / PR
# ---------------------------------------------------------------------------


@APP.route("/draft")
def draft_form():
    report_id = request.args.get("report_id", "")
    report = REPORTS.get(report_id, {})
    suggested_action = request.args.get("action", "")
    return render_template("draft.html", report=report, report_id=report_id, suggested_action=suggested_action)


@APP.route("/draft/run", methods=["POST"])
def draft_run():
    draft_source = request.form.get("draft_source", "instruction")
    report_id = request.form.get("report_id", "").strip()
    artifact_type = request.form.get("artifact_type", "issue")
    instruction = request.form.get("instruction", "").strip()
    repo_input = request.form.get("repo", ".").strip()
    from_commit = request.form.get("from_commit", "").strip()
    to_commit = request.form.get("to_commit", "").strip()
    github_input = request.form.get("github_repo_input", "").strip()
    token = request.form.get("github_token", "").strip()
    head_branch = request.form.get("head_branch", "").strip()

    report = REPORTS.get(report_id, {}) if report_id else {}
    if draft_source == "review" and report:
        repo_input = report.get("repo_input") or repo_input
        if not from_commit:
            from_commit = (report.get("from_commit") or "").strip()
        if not to_commit:
            to_commit = (report.get("to_commit") or "").strip()

    local_path = report.get("local_path") if (draft_source == "review" and report.get("local_path")) else _local_path(repo_input)
    github_owner, github_repo_name = _parse_github_repo(github_input or repo_input)
    action = f"create_{artifact_type}"

    try:
        llm = _create_llm()
        orchestrator = MultiAgentOrchestrator(llm)
    except Exception as exc:
        flash(f"LLM error: {exc}", "danger")
        return redirect(url_for("draft_form"))

    try:
        if draft_source == "review":
            from pathlib import Path
            tools = Tools(Path(local_path).resolve())
            if not tools.is_git_repo():
                flash("Not a git repository. Check the repo path.", "danger")
                return redirect(url_for("draft_form"))

            compare_mode = (report.get("compare_mode") or "").strip() if report else ""
            base_branch = (report.get("base_branch") or "").strip() if report else ""
            if compare_mode == "commits":
                if from_commit and to_commit:
                    diff_result = tools.diff_from_commits(from_commit, to_commit)
                    commit_msgs = tools.commit_messages(from_commit, to_commit)
                elif from_commit:
                    diff_result = tools.diff_from_commits(f"{from_commit}~1", from_commit)
                    commit_msgs = []
                else:
                    flash("No commit context found for this review report.", "danger")
                    return redirect(url_for("draft_form"))
            else:
                diff_result = tools.diff_from_branch(base_branch or None)
                commit_msgs = []
            package = orchestrator.run_review_and_draft(diff_result, commit_msgs, action, instruction)
        else:
            package = orchestrator.run_explicit_draft(instruction, artifact_type)
    except Exception as exc:
        flash(f"Agent error: {exc}", "danger")
        return redirect(url_for("draft_form"))

    draft_id = str(uuid.uuid4())
    data = _package_to_dict(package)
    data["github_owner"] = github_owner
    data["github_repo"] = github_repo_name
    data["github_token"] = token
    data["head_branch"] = head_branch
    PENDING_DRAFTS[draft_id] = data

    return redirect(url_for("draft_approve", draft_id=draft_id))


@APP.route("/draft/approve")
def draft_approve():
    draft_id = request.args.get("draft_id", "")
    if not draft_id or draft_id not in PENDING_DRAFTS:
        flash("Draft not found or expired.", "warning")
        return redirect(url_for("draft_form"))
    return render_template("approve.html", data=PENDING_DRAFTS[draft_id], draft_id=draft_id)


@APP.route("/draft/confirm", methods=["POST"])
def draft_confirm():
    draft_id = request.form.get("draft_id", "")
    decision = request.form.get("decision", "reject")

    if not draft_id or draft_id not in PENDING_DRAFTS:
        flash("Draft not found or expired.", "warning")
        return redirect(url_for("draft_form"))

    data = PENDING_DRAFTS.pop(draft_id)

    if decision != "approve":
        flash("Draft rejected — nothing was created on GitHub.", "info")
        return redirect(url_for("draft_form"))

    owner = data.get("github_owner", "")
    repo_name = data.get("github_repo", "")
    token = data.get("github_token", "")
    draft_type = data.get("draft_type", "issue")
    draft = data.get("draft", {})

    if not owner or not repo_name or not token:
        flash("GitHub repository and token are required to create content.", "danger")
        return redirect(url_for("draft_form"))

    try:
        api = GitHubAPI(token=token)
        if draft_type == "issue":
            created = api.create_issue(owner, repo_name, draft.get("title", ""), _format_issue_body(draft), draft.get("labels", []))
            flash(f"Issue created: {created.get('html_url', '')}", "success")
        else:
            head_branch = data.get("head_branch", "")
            if not head_branch:
                flash("Head branch is required for PR creation.", "danger")
                return redirect(url_for("draft_form"))
            created = api.create_pr(owner, repo_name, draft.get("title", ""), _format_pr_body(draft), head_branch, draft.get("base_branch", "main"))
            flash(f"Pull request created: {created.get('html_url', '')}", "success")
    except GitHubAPIError as exc:
        flash(f"GitHub API error: {exc}", "danger")
    except Exception as exc:
        flash(f"Unexpected error: {exc}", "danger")

    return redirect(url_for("draft_form"))


# ---------------------------------------------------------------------------
# Task 3 — Improve Existing Issue / PR
# ---------------------------------------------------------------------------


@APP.route("/improve")
def improve_form():
    return render_template("improve.html")


@APP.route("/improve/run", methods=["POST"])
def improve_run():
    repo_input = request.form.get("github_repo_input", "").strip()
    token = request.form.get("github_token", "").strip()
    content_type = request.form.get("content_type", "issue")
    item_num_str = request.form.get("item_num", "").strip()

    if not item_num_str.isdigit():
        flash("Issue/PR number must be a positive integer.", "danger")
        return redirect(url_for("improve_form"))

    item_num = int(item_num_str)
    github_owner, github_repo_name = _parse_github_repo(repo_input)

    if not github_owner or not github_repo_name:
        flash("Could not parse a GitHub repository from the input. Use owner/repo or a GitHub URL.", "danger")
        return redirect(url_for("improve_form"))
    if not token:
        flash("GitHub token is required.", "danger")
        return redirect(url_for("improve_form"))

    try:
        api = GitHubAPI(token=token)
        existing = api.get_issue(github_owner, github_repo_name, item_num) if content_type == "issue" else api.get_pr(github_owner, github_repo_name, item_num)
    except GitHubAPIError as exc:
        flash(f"GitHub API error: {exc}", "danger")
        return redirect(url_for("improve_form"))

    try:
        orchestrator = MultiAgentOrchestrator(_create_llm())
        result = orchestrator.run_improve(existing, content_type)
    except Exception as exc:
        flash(f"Agent error: {exc}", "danger")
        return redirect(url_for("improve_form"))

    improve_id = str(uuid.uuid4())
    IMPROVE_RESULTS[improve_id] = {
        **result,
        "github_owner": github_owner,
        "github_repo": github_repo_name,
        "github_token": token,
        "item_num": item_num,
    }
    return redirect(url_for("improve_result", improve_id=improve_id))


@APP.route("/improve/result")
def improve_result():
    improve_id = request.args.get("improve_id", "")
    if not improve_id or improve_id not in IMPROVE_RESULTS:
        flash("Result not found or expired.", "warning")
        return redirect(url_for("improve_form"))
    return render_template("improve_result.html", data=IMPROVE_RESULTS[improve_id], improve_id=improve_id)


@APP.route("/improve/post", methods=["POST"])
def improve_post():
    improve_id = request.form.get("improve_id", "")
    if not improve_id or improve_id not in IMPROVE_RESULTS:
        flash("Result not found or expired.", "warning")
        return redirect(url_for("improve_form"))

    data = IMPROVE_RESULTS.pop(improve_id)
    comment_body = _format_improvement_comment(data.get("improved", {}), data.get("content_type", "issue"), data.get("critique", {}))

    try:
        api = GitHubAPI(token=data["github_token"])
        result = api.add_comment(data["github_owner"], data["github_repo"], data["item_num"], comment_body)
        flash(f"Suggestion posted: {result.get('html_url', '')}", "success")
    except Exception as exc:
        flash(f"Error posting comment: {exc}", "danger")

    return redirect(url_for("improve_form"))


def run_app(host: str = "127.0.0.1", port: int = 5000):
    APP.run(host=host, port=port, debug=False)


if __name__ == "__main__":
    run_app()
